basePath: /
host: localhost:8001
info:
  contact: {}
  description: This API is comsumed by the simulator for the course DevOps, Software
    Evolution and Software Maintenance @ ITU Spring 2021
  termsOfService: http://swagger.io/terms/
  title: Minitwit API
  version: "1.0"
paths:
  /latest:
    get:
      description: Get the latest x
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Get the latest x
  /msgs:
    get:
      description: Gets the latest messages in descending order.
      parameters:
      - description: Number of results returned
        in: query
        name: "no"
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "403":
          description: unauthorized
          schema:
            type: string
      summary: Gets the latest messages
swagger: "2.0"
