version: '3.9'

services:
  minitwut-app:
    image: heyjoakim/mt-cmp:latest
    build:
      context: .
    ports:
      - '8000:8000'
  datadog:
    links:
     - minitwut-app # Connect the Datadog Agent container to the Go container
    image: gcr.io/datadoghq/agent:latest
    environment:
     - DD_API_KEY=${DATADOG_API_KEY}
     - DD_SITE=datadoghq.com
     - DD_DOGSTATSD_NON_LOCAL_TRAFFIC="true"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro