info:
  contact: {}
paths:
  /api/fllws/{username}:
    get:
      consumes:
      - application/json
      description: Returns a list of users followers
      parameters:
      - description: Number of results returned
        in: query
        name: "no"
        type: integer
      - description: Something about latest
        in: query
        name: latest
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "401":
          description: unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get followers
    post:
      consumes:
      - application/json
      description: follows a user, unfollows a user
      parameters:
      - description: Something about latest
        in: query
        name: latest
        type: integer
      responses:
        "204":
          description: No Content
          schema:
            type: object
        "401":
          description: unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Follows a user, unfollows a user
  /api/latest:
    get:
      description: Get the latest x
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Get the latest x
  /api/msgs:
    get:
      description: Gets the latest messages in descending order.
      parameters:
      - description: Number of results returned
        in: query
        name: "no"
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "401":
          description: unauthorized
          schema:
            type: string
      summary: Gets the latest messages
  /api/msgs/{username}:
    get:
      description: Gets the latest messages in descending order from a specific user.
      parameters:
      - description: Username
        in: query
        name: username
        required: true
        type: string
      - description: Number of results returned
        in: query
        name: "no"
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "401":
          description: unauthorized
          schema:
            type: string
      summary: Gets the latest messages from a specific user
    post:
      description: Creates a message from a specific user.
      parameters:
      - description: Username
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "401":
          description: unauthorized
          schema:
            type: string
      summary: Create a message from user
  /api/register:
    post:
      consumes:
      - application/json
      description: Registers a user, provided that the given info passes all checks.
      produces:
      - application/json
      responses:
        "203":
          description: ""
        "400":
          description: unauthorized
          schema:
            type: string
      summary: Registers a user
swagger: "2.0"
