
name: "Update and check dependency data"


on:
  pull_request:
    branches:
      - main


jobs:
  licensed:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v1
      - uses: jonabc/setup-licensed@v1
        with:
         version: 2.x
                  
      - run: go get
      
      - run : licensed cache
      - run : licensed status         
      - run: licensed list
