name: Tests
on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v2
      - 
        name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.0'
      - 
        name: Install dependencies
        run: |
          go version
      -
        name: Run GO build
        run: go build . 
      - 
        name: Run GO testing
        run: go test -v ./...
        env:
          ENVIRONMENT: testing
