name: Build & Deploy
on:
  push:
    branches: [feature/jh-compose]

jobs:
  deploy:
    runs-on: ubuntu-19.03
    steps:
      - name: Deploy GO app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          
          script: |
            mkdir src
            cd src
            git clone git@github.com:heyjoakim/devops-21.git
            echo 'Deployment successful to Digital Ocean : mt-cmp'
