name: Build & Deploy
on:
  push:
    branches: [main]
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v2
      - 
        name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.0'
      - 
        name: Install dependencies
        run: |
          go version
      -
        name: Run GO build
        run: go build . 
      - 
        name: Run GO testing
        run: go test -v ./...
        env:
          ENVIRONMENT: testing
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: heyjoakim/mt-cmp:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      
      -
        name: Deploy GO app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          
          script: |
            mkdir src
            cd src
            git clone git@github.com:heyjoakim/devops-21.git
            cd devops-21
            git pull
            docker-compose pull
            docker-compose up -d
      - 
        name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      

