name: Build & Deploy
on:
  push:
    branches: [feature/jh-compose]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        ½name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: heyjoakim/mt-cmp:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      

#      -
#        name: Deploy GO app
#        uses: appleboy/ssh-action@v0.1.2
#        with:
#          host: ${{secrets.SSH_HOST}}
#          key: ${{secrets.SSH_KEY}}
#          username: ${{secrets.SSH_USERNAME}}
#          passphrase: ${{ secrets.SSH_PASSPHRASE }}
#          
#          script: |
#            mkdir src
#            cd src
#           git clone git@github.com:heyjoakim/devops-21.git
#           cd devops-21
#           docker-compose pull
#            docker-compose up -d
      

