name: Build report

on:
  push:
    branches: [report/*]
  pull_request:
    branches: [report/*]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - run: |
          echo hello > 01ab.txt
      - name: Commit files
        run: |
          git config --global user.email "joakimhey@gmail.com"
          git config --global user.name "heyjoakim"
          git add .
          git status
          git commit -m "Add changes" -a
          git push https://github.com/heyjoakim/devops-21.git
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
          repository: heyjoakim/devops-21
