name: Go

on:
  push:
    branches: [  final/report ]
  pull_request:
    branches: [  final/report ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build report
      run: pwd
