name: Build report

on:
  push:
    branches: [report/*]
  pull_request:
    branches: [report/*]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v2
    - 
      name: Create artifact files
      run: |
        mkdir -p path/to/dir-1
        echo "Lorem ipsum dolor sit amet" > path/to/dir-1/file1.txt
    - name: 'Upload artifact #1'
      uses: ./
      with:
        name: 'Artifact-A'
        path: path/to/dir-1/file1.txt
