name: Build report

on:
  push:
    branches: [report/*]
  pull_request:
    branches: [report/*]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: report/build/main.tex
          latexmk_use_xelatex: true
      - name: Commit files
        run: |
          git config --local user.email "joakimhey@gmail.com"
          git config --local user.name "heyjoakim"
          git add -A
          git commit -m "Add changes" -a
          git push
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
