name: Build report

on:
  push:
    branches: [report/*]
  pull_request:
    branches: [report/*]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: | 
        echo hello > world.txt
        pwd
        ls
        cat world.txt
        git pull
        git add world.txt
        git push
