name: Build report

on:
  push:
    branches: [report/*]
  pull_request:
    branches: [report/*]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
         pwd
         ls
         cd report/build
      - name: Commit report
        run: |
          git config --global user.name 'heyjoakim'
          git config --global user.email 'heyjoakim@users.noreply.github.com'
          git add .
          git commit -m "Automated report"
          git push
