name: Build report

on:
  push:
    branches: [report/*]
  pull_request:
    branches: [report/*]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v2
    - 
      name: Build latex file
      run: |
        cd report/build
        pwd
        make main.pdf
        pwd
    - 
      name: Upload
      uses: actions/upload-artifact@master
      with:
        name: main
        path: report/build/
