name: Build report

on:
  push:
    branches: [report/*]
  pull_request:
    branches: [report/*]
    
  workflow_dispatch:
  
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: echo hello2 > report.txt
      - name: Commit report
        run: |
          git config --global user.name 'heyjoakim'
          git config --global user.email 'joakimhey@gmail.com'
          git add report.txt
          git commit -am "Automated report"
          git push
