name: Build report

on:
  push:
    branches: [report/*]
  pull_request:
    branches: [report/*]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - run: |
          echo hello > 01ab.txt
      - name: Commit report
        run: |
          git config --global user.name 'heyjoakim'
          git config --global user.email 'heyjoakim@users.noreply.github.com'
          git add -A
          git commit -am "Automated report"
          git push origin :refs/tags/refs/heads/master
          git tag -d refs/heads/master
          git push
