name: Build report

on:
  push:
    branches: [report/*]
  pull_request:
    branches: [report/*]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: mkdir -p a1/s1

    - run: echo hello > world.txt

    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: world.txt
