name: Build report

on:
  push:
    branches: [report/*]
  pull_request:
    branches: [report/*]
    
  workflow_dispatch:
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repository
    - uses: actions/checkout@v2
    - name: Github Action for LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: main
        path: main
